<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>Nullable</WarningsAsErrors>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>GenshinImpactAutoMusic</RootNamespace>
		<AssemblyName>GenshinImpactAutoMusic</AssemblyName>
		<ApplicationIcon>Resources\Ward_Shield_Transparent_Background.ico</ApplicationIcon>
		<Version>1.0.0</Version>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
		<PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
		<EmbeddedResource Include="Resources\Ward_Shield_Transparent_Background.ico" LogicalName="GenshinImpactAutoMusic.Resources.Ward_Shield_Transparent_Background.ico" />
		<EmbeddedResource Include="Resources\Ward_Shield_Transparent_Background.png" LogicalName="GenshinImpactAutoMusic.Resources.Ward_Shield_Transparent_Background.png" />
		<ProjectReference Include="..\..\SettingsFile\SettingsFile\SettingsFile.csproj" />
		<ProjectReference Include="..\..\Ward Shield Splash Window\WardShieldSplashWindow.csproj" />
		<Resource Include="Resources\Kofi.png" />
		<Resource Include="Resources\GitHub.png" />
		<Resource Include="Resources\Sponsor.png" />
	</ItemGroup>
</Project>